sudo: false
language: node_js
node_js:
  - node
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
before_install:
  - openssl aes-256-cbc -K $encrypted_a90f6951030a_key -iv $encrypted_a90f6951030a_iv -in deploy_key.enc -out ../deploy_key -d
  - chmod 600 ../deploy_key
install:
  - npm install
  - pip install --user -r requirements.txt
script:
  - npm run build
  - npm run publish
env:
  global:
    - ENCRYPTION_LABEL: "a90f6951030a"
